/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg05.gui.agenda;

import java.util.ArrayList;

/**
 *
 * @author m
 */
public class Agenda extends javax.swing.JFrame {



private MenuPrincipal menuPrincipal;

	public void setMenuPrincipal(MenuPrincipal menuPrincipal) {
		this.menuPrincipal = menuPrincipal;
	}


    int contador=1;
/**
 * Creates new form Agenda
 */
public Agenda() {
	initComponents();
        verAgenda();
	}
public void verAgenda(){
	if (DatosAgenda.getContactos().size()>0){
        jTextArea1.setText("\n"+"  Nombre: "+DatosAgenda.getContactos().get(contador-1).getNombre()+"\n"+"\n"
                +"  Teléfono: "+DatosAgenda.getContactos().get(contador-1).getTelefono()+"\n"+"\n"
                +"  Email: "+DatosAgenda.getContactos().get(contador-1).getEmail()+"\n"+"\n");
       
        
            jTextField1.setText("\n"+" "+(contador)+" de "+DatosAgenda.getContactos().size());
        
        
}}

/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("AGENDA");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg05/gui/agenda/backward.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 248, 140, 110));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg05/gui/agenda/forward.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 238, 130, 120));

        jTextArea1.setBackground(getBackground());
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setAutoscrolls(false);
        jTextArea1.setOpaque(false);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 490, 210));

        jTextField1.setBackground(getBackground());
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 90, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        
        if (contador>1){
            contador--;
        jTextArea1.setText("\n"+"  Nombre: "+DatosAgenda.getContactos().get(contador-1).getNombre()+"\n"+"\n"
                +"  Teléfono: "+DatosAgenda.getContactos().get(contador-1).getTelefono()+"\n"+"\n"
                +"  Email: "+DatosAgenda.getContactos().get(contador-1).getEmail()+"\n"+"\n");
        
        jTextField1.setText("\n"+" "+(contador)+" de "+DatosAgenda.getContactos().size());
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
         
        if(contador<DatosAgenda.getContactos().size()){
            contador++;
        jTextArea1.setText("\n"+"  Nombre: "+DatosAgenda.getContactos().get(contador-1).getNombre()+"\n"+"\n"
                +"  Teléfono: "+DatosAgenda.getContactos().get(contador-1).getTelefono()+"\n"+"\n"
                +"  Email: "+DatosAgenda.getContactos().get(contador-1).getEmail()+"\n"+"\n");
        
        jTextField1.setText("\n"+" "+(contador)+" de "+DatosAgenda.getContactos().size());}
    }//GEN-LAST:event_jLabel2MouseClicked

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
		for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
			if ("Nimbus".equals(info.getName())) {
				javax.swing.UIManager.setLookAndFeel(info.getClassName());
				break;
			}
		}
	} catch (ClassNotFoundException ex) {
		java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
		java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
		java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
		java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	public void run() {
		new Agenda().setVisible(true);
	}
	});
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
